server:
  address: "corecast.bitquery.io"
  authorization: "ory_at_" # Get auth token at https://account.bitquery.io/user/api_v2/access_tokens
  insecure: false

stream:
  type: "dex_trades"

# Trade filtering option
# Options: "alltrades", "buys", "sells"
# - alltrades: Show all trades involving the token
# - buys: Show only trades where the token is being BOUGHT (token is on buy side)
# - sells: Show only trades where the token is being SOLD (token is on sell side)

# Filter for specific token trades on LetsBonk.fun
trade_filter: "alltrades"
filters:
  programs:
    - "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj" # LetsBonk.fun
  tokens:
    - "CHNxstQ6zsj9b7QMmCKbnJkhyKwoTL19bPe6VYoebonk" # Example token

# ============================================================================
# LETSBONK.FUN EXAMPLES
# ============================================================================

# Example 1: Monitor ALL trades for a specific token on LetsBonk.fun
# trade_filter: "alltrades"
# filters:
#   programs:
#     - "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj"
#   tokens:
#     - "CHNxstQ6zsj9b7QMmCKbnJkhyKwoTL19bPe6VYoebonk"

# Example 2: Monitor only BUYS for a specific token on LetsBonk.fun
# trade_filter: "buys"
# filters:
#   programs:
#     - "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj"
#   tokens:
#     - "CHNxstQ6zsj9b7QMmCKbnJkhyKwoTL19bPe6VYoebonk"

# Example 3: Monitor only SELLS for a specific token on LetsBonk.fun
# trade_filter: "sells"
# filters:
#   programs:
#     - "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj"
#   tokens:
#     - "CHNxstQ6zsj9b7QMmCKbnJkhyKwoTL19bPe6VYoebonk"

# Example 4: Monitor multiple tokens on LetsBonk.fun
# trade_filter: "alltrades"
# filters:
#   programs:
#     - "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj"
#   tokens:
#     - "CHNxstQ6zsj9b7QMmCKbnJkhyKwoTL19bPe6VYoebonk"
#     - "4FBx5RBfEuuhkT5RB7kJ46WC6cL9J4SJNXyKeoDAbonk"

# Example 5: Monitor buying activity for a specific trader
# trade_filter: "buys"
# filters:
#   programs:
#     - "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj"
#   tokens:
#     - "CHNxstQ6zsj9b7QMmCKbnJkhyKwoTL19bPe6VYoebonk"
#   traders:
#     - "YourWalletAddressHere"

# ============================================================================
# NOTES
# ============================================================================
#
# - Raydium Launchlab Program: LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj
# - All LetsBonk.fun tokens trade on Raydium Launchlab
# - Trades are filtered server-side by program and token
# - Buy/Sell filtering happens client-side for better control
#
# ============================================================================
